### ISSUE TITLE
Tracking issue: Rename app ID to `so.libdb.gtkcord4`

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gtkcord4#156]
Originally, `xyz.diamondb.gtkcord4` is used as the ID. However, I no longer own diamondb.xyz, so the ID should be updated.

Questions:

- How much of the user will this break?
- Will this affect Flatpak users much?

Action Items:

- [x] Update repository XML, application code and its .desktop file
- [x] Update Arch package
- [x] Update Flatpak package
- [x] Update NixOS package (is this still a thing?)
- Add to this list more packages that I missed.

cc @milkknife @urandom2 @Aleksanaa @hmenke

**Comment by milkknife** [comment]
For flatpak, this line will need to be changed for it to work alongside dbus: [main.go#L46](https://github.com/diamondburned/gtkcord4/blob/main/main.go#L46).
as a stopgap I can include a patch in [flathub/xyz.diamondb.gtkcord4](https://github.com/flathub/xyz.diamondb.gtkcord4) which changes the app ID in that file.

Likewise I will ask the flathub maintainers about it, although I think they may not agree to this.

**Comment by milkknife** [comment]
The flatpak has been renamed:
- https://github.com/flathub/so.libdb.gtkcord4
- https://github.com/flathub/xyz.diamondb.gtkcord4/blob/master/flathub.json

**Comment by txtsd** [comment]
All 3 Arch packages have been updated to use `so.libdb.gtkcord4`

[gtkcord4](https://aur.archlinux.org/packages/gtkcord4)
[gtkcord4-bin](https://aur.archlinux.org/packages/gtkcord4-bin)
[gtkcord4-git](https://aur.archlinux.org/packages/gtkcord4-git)

You can update the checklist. Feel free to ping me for Arch/AUR stuff in the future.

**Comment by diamondburned** [comment]
Closing as everything has been migrated over.
